[package]
name = "qxr_bridge"
version = "0.1.0"
edition = "2021"

[lib]
name = "qxr_bridge"
crate-type = ["cdylib", "staticlib"]

[dependencies]
libc = "0.2"

[features]
default = []
python-bindings = []